name: Release package version
description: Release package version based on package.json

inputs:
  token:
    type: string
    required: true
    description: "GitHub token"
  npm_token:
    type: string
    required: true
    description: "NPM token"

runs:
  using: "composite"
  steps:
    # Set up Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Setup Node JS environment for npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Determine tag for npm publish
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/next" ]]; then
            echo "TAG=prerelease" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Publish to npm
        run: npm publish --access public --tag ${{ env.TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ inputs.npm_token }}

      - name: Setup node to publish to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@revolist'

      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ inputs.token }}
          
