name: Build and publish package version to NPM and GitHub Packages

inputs:
  token:
    type: string
    required: true
    description: "GitHub token"
  npm_token:
    type: string
    required: true
    description: "NPM token"
  path:
    type: string
    required: false
    description: "Path to package code"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22.4.x

    - name: Setup Node JS environment for npm
      uses: actions/setup-node@v4
      with:
        node-version: 22.4.x
        registry-url: 'https://registry.npmjs.org'

    - run: npm i
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Determine tag for npm publish
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/next" ]]; then
          echo "TAG=prerelease" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Publish to npm
      id: npm-publish
      continue-on-error: true
      run: npm publish --provenance --access public --tag ${{ env.TAG }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
      shell: bash
      working-directory: ${{ inputs.path || '.' }}

    - name: Setup node to publish to GitHub Packages
      if: always()
      uses: actions/setup-node@v4
      with:
        node-version: 22.4.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@revolist'

    - name: Publish to GitHub Packages
      if: always()
      run: npm publish --access public --tag ${{ env.TAG }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      shell: bash
      working-directory: ${{ inputs.path || '.' }}
          
