name: Release package version
description: Release package version based on package.json

inputs:
  token:
    type: string
    required: true
    description: "GitHub token"
  npm_token:
    type: string
    required: true
    description: "NPM token"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Setup Node JS environment for npm
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm i
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Determine tag for npm publish
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/next" ]]; then
          echo "TAG=prerelease" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Publish to npm
      run: npm publish --access public --tag ${{ env.TAG }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
      shell: bash

    - name: Setup node to publish to GitHub Packages
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@revolist'

    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      shell: bash
          
