name: Build and publish package version to NPM and GitHub Packages

inputs:
  token:
    type: string
    required: true
    description: "GitHub token"
  npm_token:
    type: string
    required: true
    description: "NPM token"
  path:
    type: string
    required: false
    description: "Path to package code"

runs:
  using: "composite"
  steps:

    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Debug npm token - whoami
      run: npm whoami || echo "npm whoami failed"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
      shell: bash

    - name: Install dependencies
      run: npm i
      shell: bash

    - name: Build
      run: npm run build
      shell: bash