name: Build and publish package version to NPM and GitHub Packages

inputs:
  token:
    type: string
    required: true
    description: "GitHub token"
  npm_token:
    type: string
    required: true
    description: "NPM token"
  path:
    type: string
    required: false
    description: "Path to package code"

runs:
  using: "composite"
  steps:

    - uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'

    - run: npm i
      shell: bash
      env:
        NODE_AUTH_TOKEN: ''

    - name: Build
      run: npm run build
      shell: bash